<?php

use Illuminate\Support\Facades\Auth;
use Symfony\Component\HttpFoundation\Request;

$authUser = Auth::user();
$lang_key = 'en';
$company_id = $authUser->company_id ?? null;

?>


<script>

    var TRANSLATED_LABELS = {
        lblConnectServerFailed : "{{ __('Cannot connect to server!') }}",
        lblHeaderDelete         : "{{ __('Confirm Delete') }}",
        lblConfirmDelete         : "{{ __('Are you sure you want to delete this record?') }}",
        lblConfirmDeleteAll         : "{{ __('Are you sure you want to delete all this record?') }}",
        lblDeletingData         : "{{ __('Deleting Data') }}",
        lblDeletingDataContent         : "{{ __('Please wait a few seconds') }}",

    };

    var HRMS_LABELS = {
        lblNo: "{{ __("No.") }}",
        lblEmpId: "{{ __("Emp.ID") }}",
        lblCode: "{{ __("Code") }}",
        lblName: "{{ __("Name") }}",
        lblDescription: "{{ __("Description") }}",
        lblAction: "{{ __("Action") }}",
        lblInsert: "{{ __("Add new") }}",
        lblEdit: "{{ __("Edit") }}",
        lblDelete: "{{ __("Delete") }}",
        lblFromDate: "{{ __("From date") }}",
        lblToDate: "{{ __("To date") }}",
        lblActive: "{{ __("Active") }}",
        lblFind: "{{ __("Find") }}",
        lblWorkingDays: "{{ __("Working days") }}",
        lblSocialInsurance: "{{ __("Social Insurance") }}",
        lblTax: "{{ __("Tax") }}",
        lblNote: "{{ __("Note") }}",
        lblShortName: "{{ __("Short Name") }}",
        lblLocked: "{{ __("Locked") }}",
        lblCountryCode: "{{ __("Country Code") }}",
        lblPaymentRate: "{{ __("Payment Rate") }}",
        lblWorkStart: "{{ __("Work Start") }}",
        lblWorkEnd: "{{ __("Work End") }}",
        lblRelaxStart: "{{ __("Relax Start") }}",
        lblRelaxEnd: "{{ __("Relax End") }}",
        lblDayOff: "{{ __("Day Off") }}",
        lblFromTime: "{{ __("From Time") }}",
        lblToTime: "{{ __("To Time") }}",
        lblNightShift: "{{ __("Night Shift") }}",
        lblDefaultOTEarlyType: "{{ __("Default OT Early Type") }}",
        lblDefaultOTLateType: "{{ __("Default OT Late Type") }}",
        lblFuelPrice: "{{ __("Fuel Price") }}",
        lblDistance: "{{ __("Distance") }}",
        lblAllowance: "{{ __("Allowance") }}",
        lblApplyFromDate: "{{ __("Apply From Date") }}",
        lblApplyDate: "{{ __("Apply Date") }}",
        lblKeySearch: "{{ __("Key Search") }}",
        lblCreatedAt: "{{ __("Created At") }}",
        lblPrimaryAddress: "{{ __("Primary Address") }}",
        lblSecondAddress: "{{ __("Second Address") }}",
        lblFaxNumber: "{{ __("Fax Number") }}",
        lblLeaveCategory: "{{ __("Leave Category") }}",
        lblAmount: "{{ __("Amount") }}",
        lblIsManager: "{{ __("Is Manager") }}",
        lblIsGa: "{{ __("Is GA") }}",
        lblImport: "{{ __("Import") }}",
        lblExport: "{{ __("Export") }}",
        lblImportData: "{{ __("Import Data") }}",
        lblImporting: "{{ __("Importing data...") }}",
        lblImportingMessage: "{{ __("Please wait a few seconds when system importing data!") }}",
        lblExporting: "{{ __("Exporting data...") }}",
        lblSelectFile: "{{ __("Select File") }}",
        lblWarningWrongExcelFile: "{{ __("Please select file Excel") }}",
        lblWarningEmptyFile: "{{ __("File import can not empty!") }}",
        lblClose: "{{ __("Close") }}",
        lblDownloadSample: "{{ __("Sample") }}",
        lblWorkingDay: "{{ __("Working Days") }}",
        lblWorkingHour: "{{ __("Working Hours") }}",
        lblDepartment: "{{ __("Department") }}",
        lblPosition: "{{ __("Position") }}",
        lblJoinDate: "{{ __("Join Date") }}",
        lblPhone: "{{ __("Phone") }}",
        lblContactEmail: "{{ __("Contact Email") }}",
        lblContinueAdd: "{{ __("Continue add") }}",
        lblWarningEmptyCode: "{{ __("Please fill employee code before click insert button!") }}",
        lblProfile: "{{ __("Profile") }}",
        lblWarningUpdateCodeBefore: "{{ __("Please update code for employee before!") }}",
        lblDivision: "{{ __("Division") }}",
        lblSave         : "{{ __('Save') }}",
        lblCancel         : "{{ __('Cancel') }}",
        lblFullName         : "{{ __('Full name') }}",
        lblNickname         : "{{ __('Nick name') }}",
        lblEngName         : "{{ __('English name') }}",
        lblEmployeeCode         : "{{ __('Employee code') }}",
        lblManagerCode         : "{{ __('Manager code') }}",
        lblGender         : "{{ __('Gender') }}",
        lblMale         : "{{ __('Gender') }}",
        lblFemale         : "{{ __('Female') }}",
        lblOther         : "{{ __('Other') }}",
        lblGeneral         : "{{ __('General') }}",
        lblManagerOneCode         : "{{ __('Manager 1 Code') }}",
        lblManagerTwoCode         : "{{ __('Manager 2 Code') }}",
        lblUploadAvatar         : "{{ __('Upload Avatar') }}",
        lblAvatar         : "{{ __('Avatar') }}",
        lblInsertImage         : "{{ __('Insert Image') }}",
        lblRequireEnterEmployeeCode         : "{{ __('Please enter employee code!') }}",
        lblWorkInfo         : "{{ __('Work Information') }}",
        lblGroupName         : "{{ __('Group Name') }}",
        lblFamilyInfo         : "{{ __('Family Information') }}",
        lblFamilyRelationship         : "{{ __('Family Relationship') }}",
        lblCarrier         : "{{ __('Carrier') }}",
        lblBirthday         : "{{ __('Birthday') }}",
        lblNationId         : "{{ __('Nation ID') }}",
        lblEffectiveDate         : "{{ __('Effective Date') }}",
        lblEffectiveToDate         : "{{ __('Effective to Date') }}",
        lblAddress         : "{{ __('Address') }}",
        lblTaxDeduct         : "{{ __('Tax Deduct') }}",
        lblCompanyName         : "{{ __('Company Name') }}",
        lblSalary         : "{{ __('Salary') }}",
        lblCompanyAddress         : "{{ __('Company Address') }}",
        lblReason         : "{{ __('Reason') }}",
        lblWorkingHistories         : "{{ __('Working Histories') }}",
        lblSkills         : "{{ __('Skills') }}",
        lblSkill         : "{{ __('Skill') }}",
        lblQualifications         : "{{ __('Qualifications') }}",
        lblQualification         : "{{ __('Qualification') }}",
        lblLevelGrade         : "{{ __('Level/Grade') }}",
        lblObtainedDate         : "{{ __('Obtained Date') }}",
        lblIssued         : "{{ __('Issued') }}",
        lblNameOfCourse         : "{{ __('Name of Course') }}",
        lblOrganizeBy         : "{{ __('Organize by') }}",
        lblEducations         : "{{ __('Educations') }}",
        lblEducation         : "{{ __('Education') }}",
        lblPlace         : "{{ __('Place') }}",
        lblMajor         : "{{ __('Major') }}",
        lblLaborContracts         : "{{ __('Labor Contracts') }}",
        lblContractType         : "{{ __('Contract Type') }}",
        lblPersonal         : "{{ __('Personal') }}",
        lblBirthdayPlace         : "{{ __('Birthday Place') }}",
        lblReligion         : "{{ __('Religion') }}",
        lblCountry         : "{{ __('Country') }}",
        lblMarriedYN         : "{{ __('Married[Y/N]') }}",
        lblPrivateEmail         : "{{ __('Private Email') }}",
        lblPersonalEmail         : "{{ __('Personal Email') }}",
        lblCompanyEmail         : "{{ __('Company Email') }}",
        lblPermanentAddress         : "{{ __('Permanent Address') }}",
        lblTempAddress         : "{{ __('Temp Address') }}",
        lblTransport         : "{{ __('Transport') }}",
        lblTimeKeepingId         : "{{ __('Time Keeping ID') }}",
        lblIP         : "{{ __('IP') }}",
        lblDirection         : "{{ __('Direction') }}",
        lblFactory         : "{{ __('Factory') }}",
        lblImportEmployees         : "{{ __('Import Employees') }}",
        lblRefresh         : "{{ __('Refresh') }}",
        lblBrowse         : "{{ __('Browse...') }}",
        lblSyncing         : "{{ __('Syncing') }}",
        lblSyncingLeaveData         : "{{ __('Syncing Leave Data') }}",
        lblSync         : "{{ __('Sync') }}",
        lblCreateWorkDay         : "{{ __('Create Work Day') }}",
        lblYear         : "{{ __('Year') }}",
        lblMonth         : "{{ __('Month') }}",
        lblUserCode         : "{{ __('User Code') }}",
        lblImportAnnualLeave         : "{{ __('Import Annual Leave') }}",
        lblSalaryMatrix         : "{{ __('Salary Matrices') }}",
        lblSalaryMatrixDetail         : "{{ __('Salary Matrix Details') }}",
        lblRank         : "{{ __('Rank') }}",
        lblCoefficient         : "{{ __('Coefficient') }}",
        lblImportSalaryMatrixDetail         : "{{ __('Import Salary Matrix Details') }}",
        lblAddNew         : "{{ __('Add New') }}",
        lblCreateOffice         : "{{ __('Create Office') }}",
        lblCreateQualification         : "{{ __('Create Qualification') }}",
        lblCreateUserStatus         : "{{ __('Create Employee Status') }}",
        lblSection : "{{ __('Section') }}",
        lblSelect : "{{ __('Select') }}",
        lblKind : "{{ __('Kind') }}",
        lblPaidRate : "{{ __('Paid rate') }}",
        lblUserId: "{{ __('User ID') }}",
        lblTotalLeaveDays: "{{ __('Total Leave Days') }}",
        lblUsedLeaveDays: "{{ __('Used Leave Days') }}",
        lblRemainingLeaveDays: "{{ __('Remaining Leave Days') }}",
        lblAnnualTransfer: "{{ __('Annual Transfer') }}",
        lblTransferUsedByMarch: "{{ __('Transfer Used by March') }}",
        lblTransferCleared: "{{ __('Transfer Cleared') }}",
        lblTotalAccruedInYear: "{{ __('Total Accrued in Year') }}",
        lblHeaderDelete: "{{ __('Confirm Delete') }}",
        lblConfirmDelete: "{{ __('Are you sure you want to delete this record?') }}",
        lblDeletingData: "{{ __('Deleting Data') }}",
        lblDeletingDataContent: "{{ __('Please wait while deleting data...') }}",
        lblProcessAnnual: "{{ __('Process Annual') }}",
        lblBack: "{{ __('Back') }}",
        lblProcess: "{{ __('Process') }}",
        lblOpeningBalance: "{{ __('Opening Balance') }}",
        lblMonthlyAccrued: "{{ __('Monthly Accrued') }}",
        lblMonthlyUsed: "{{ __('Monthly Used') }}",
        lblMonthlyRemaining: "{{ __('Monthly Remaining') }}",
        lblReset: "{{ __('Reset') }}",
        lblCreateDepartment: "{{ __('Create Department') }}",
        lblTerminateDate: "{{ __('Terminate date') }}",
        lblConnectServerFailed: "{{ __('Cannot connect to server!') }}",
        lblImportant: "{{ __('Important') }}",
        lblPlease: "{{ __('Please') }}",
        lblSelectPeriod: "{{ __('Select Period') }}",
        lblExportBy: "{{ __('Export By') }}",
        lblExportAll: "{{ __('Export All') }}",
        lblExportPayrollDetail: "{{ __('Export Payroll Detail') }}",
        lblExportPayrollFull: "{{ __('Export Payroll Full') }}",
        lblCalculateSalary: "{{ __('Calculate salary') }}",
        lblSelectSalaryPeriod: "{{ __('Select Salary Period') }}",
        lblStandardWorkingDay: "{{ __('Standard Working Day') }}",
        lblCreate: "{{ __('Create') }}",
        lblIsTax: "{{ __('Is Tax') }}",
        lblIsSocialInsurance: "{{ __('Is Social Insurance') }}",
    };

    var SYSTEM_CONSTANT = {
        STATUS_ACTIVE : {!! config('constants.status.active') !!},
        DEFAULT_PAGE_SIZE : {!! config('constants.default_page_size') !!},
        STATUS_INACTIVE : {!! config('constants.status.inactive') !!},
        COMPANY_ID : "{{ $company_id }}",
        ACTION_INSERT: {!! config('constants.actions.insert') !!},
        ACTION_UPDATE: {!! config('constants.actions.update') !!},
        ACTION_DELETE: {!! config('constants.actions.delete') !!},
        ACTION_EXPORT: {!! config('constants.actions.export') !!},
        ACTION_IMPORT: {!! config('constants.actions.import') !!},
        ACTION_VIEW: {!! config('constants.actions.view') !!},
        DELETE_KEY: 46,
        DEFAULT_BUTTON_WIDTH: 120,
    };

    var MASTER_ROUTE = {
        USERS_URL : "{{ route('admin.master_data.users') }}",
        YEARS_URL : "{{ route('admin.master_data.years') }}",
        MONTHS_URL : "{{ route('admin.master_data.months') }}",
        LEAVE_TYPE_URL : "{{ route('admin.master_data.leave_types') }}",
        LEAVE_SESSION_URL : "{{ route('admin.master_data.leave_sessions') }}",
        DEPARTMENT_URL : "{{ route('admin.master_data.departments') }}",
        POSITION_URL : "{{ route('admin.master_data.positions') }}",
        SALARY_PERIOD_URL : "{{ route('admin.master_data.get_salary_period') }}",
    };

    var DEFAULT_TIME = 1;
    var SYSTEM_CACHE = "1";
    var lang_key = "{{ $lang_key }}";
    var _token = "{{ csrf_token() }}";
    var lastChange;
    // var dateFormat = lang_key == "en" ? "m/d/Y" : "d/m/Y";
    var dateFormat = "d/m/Y";
    var currentMonth = "{{ date('m') }}";
    var currentYear = "{{ date('Y') }}";
</script>
