<?php

return [
    'paginate' => 10,
    'app_version' => '1.0.0',
    'ROLE_ADMIN' => 1,
    'COMPANY_ID' => 1,
    'ROLE_CUSTOMER' => 2,
    'DATE_FORMAT' => env('DATE_FORMAT', 'd/m/Y'),
    'CHUNK_SIZE' => env('CHUNK_SIZE', 300),
    'COMPANY' => [
        'name' => env('COMPANY_NAME', 'EASYCOM CO.,LTD'),
    ],
    'SECURITY' => [
        'xlsx_password' => env('XLSX_PASSWORD', 'password1234'),
    ],
    'roles' => [
        1 => '管理者',
        2 => '顧客',
    ],
    'SOCIAL' => [
        'ZALO' => [
            'OAID' => env('ZALO_OAID', '2021130729057140123'),
            'APPID' => env('ZALO_APPID', '3700176445760170348'),
        ]
    ],
    'actions' => [
        'view' => 1,
        'insert' => 2,
        'update' => 3,
        'delete' => 4,
        'export' => 5,
        'import' => 6,
    ],
    'default_page_size' => 15,
    'status' => [
        'active' => 1,
        'inactive' => 0,
    ],
    'ot_types' => [
        1 => ['id' => 1, 'name' => 'Work day'],
        2 => ['id' => 2, 'name' => 'Work night'],
        3 => ['id' => 3, 'name' => 'Special day'],
        4 => ['id' => 4, 'name' => 'Special night'],
        5 => ['id' => 5, 'name' => 'Day-off'],
        6 => ['id' => 6, 'name' => 'Day-off night'],
    ],
    'leave_sessions' => [
        1 => ['id' => 1, 'name' => 'Sáng'],
        2 => ['id' => 2, 'name' => 'Chiều'],
        3 => ['id' => 3, 'name' => 'Cả ngày'],
    ],
    'flaticons' => [
        'flaticon-computer',
        'flaticon-chip',
        'flaticon-code',
        'flaticon-programming',
        'flaticon-cloud',
        'flaticon-brain',
        'flaticon-cpu',
        'flaticon-project-management',
        'flaticon-cpu',
        'flaticon-technical-support',
        'flaticon-chip-1',
        'flaticon-brain-1',
        'flaticon-settings',
        'flaticon-coding',
        'flaticon-targeted-marketing',
        'flaticon-protection',
        'flaticon-analysis',
        'flaticon-server',
        'flaticon-cpu-1',
        'flaticon-artificial-intelligence',
        'flaticon-super-intelligence',
        'flaticon-chip-2',
        'flaticon-light-bulb',
        'flaticon-cloud-computing',
        'flaticon-innovation',
        'flaticon-creative',
        'flaticon-stats',
        'flaticon-business',
        'flaticon-thumbs-up',
        'flaticon-puzzle',
        'flaticon-idea',
        'flaticon-analytics',
        'flaticon-development',
        'flaticon-certificate',
        'flaticon-gears',
        'flaticon-medal',
        'flaticon-mobile-app',
        'flaticon-phone-call',
        'flaticon-call',
        'flaticon-envelope',
        'flaticon-email',
        'flaticon-placeholder',
        'flaticon-location',
        'flaticon-download',
    ]
];
